"""Report service: generate a downloadable HTML orchard health report."""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy.orm import Session

from app.models import AIDetection, Alert, HistoricalMonitoring, Intervention, Orchard, OrchardZone, Scan, SensorReading
from app.services.metrics_service import compute_metrics


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def generate_html_report(db: Session, orchard_id: int) -> str:
    orchard = db.get(Orchard, orchard_id)
    if orchard is None:
        raise ValueError(f"Orchard {orchard_id} not found")

    metrics = compute_metrics(db, orchard_id)
    zones = db.query(OrchardZone).filter(OrchardZone.orchard_id == orchard_id).all()
    alerts = (
        db.query(Alert)
        .join(OrchardZone, Alert.zone_id == OrchardZone.id)
        .filter(OrchardZone.orchard_id == orchard_id)
        .order_by(Alert.created_at.desc())
        .limit(20)
        .all()
    )
    interventions = (
        db.query(Intervention)
        .join(OrchardZone, Intervention.zone_id == OrchardZone.id)
        .filter(OrchardZone.orchard_id == orchard_id)
        .order_by(Intervention.created_at.desc())
        .limit(20)
        .all()
    )
    recent_scans = (
        db.query(Scan)
        .filter(Scan.orchard_id == orchard_id)
        .order_by(Scan.timestamp.desc())
        .limit(10)
        .all()
    )

    generated = utcnow().strftime("%Y-%m-%d %H:%M UTC")

    zone_rows = "".join(
        f"<tr><td>{z.zone_name}</td><td>{z.health_status}</td>"
        f"<td>{z.risk_score:.1f}</td><td>{z.area:.2f}</td></tr>"
        for z in zones
    )
    alert_rows = "".join(
        f"<tr><td>{a.id}</td><td>{a.alert_type}</td><td>{a.severity}</td>"
        f"<td>{a.risk_score:.1f}</td><td>{a.status}</td></tr>"
        for a in alerts
    )
    intervention_rows = "".join(
        f"<tr><td>{i.id}</td><td>{i.intervention_type}</td><td>{i.target_area:.2f}</td>"
        f"<td>{i.status}</td></tr>"
        for i in interventions
    )
    scan_rows = "".join(
        f"<tr><td>{s.id}</td><td>{s.scan_type}</td><td>{s.coverage:.1f}%</td>"
        f"<td>{s.timestamp.strftime('%Y-%m-%d %H:%M')}</td></tr>"
        for s in recent_scans
    )

    html = f"""<!doctype html>
<html><head><meta charset="utf-8"><title>CitrusGuardAI Report</title>
<style>
body{{font-family:system-ui,sans-serif;margin:2rem;color:#1f3b1d}}
h1{{color:#2c5a26}} h2{{color:#37712e;border-bottom:2px solid #e0efdb;padding-bottom:.3rem}}
table{{border-collapse:collapse;width:100%;margin:1rem 0}}
th,td{{border:1px solid #c2dfba;padding:.4rem .6rem;text-align:left}}
th{{background:#f2f8f0}}
.kpi{{display:inline-block;background:#fff8eb;border:1px solid #ffdd88;border-radius:8px;
padding:.8rem 1.2rem;margin:.3rem}}
</style></head><body>
<h1>CitrusGuardAI — Orchard Health Report</h1>
<p><strong>{orchard.name}</strong> — {orchard.location}<br>
Generated: {generated} | Crop: {orchard.crop} | Area: {orchard.area} acres</p>

<h2>Key Metrics</h2>
<div>
<span class="kpi">Total Area: {metrics['total_orchard_area']:.1f} ac</span>
<span class="kpi">Monitored: {metrics['monitored_area']:.1f} ac</span>
<span class="kpi">Healthy: {metrics['healthy_area']:.1f} ac</span>
<span class="kpi">At Risk: {metrics['at_risk_area']:.1f} ac</span>
<span class="kpi">Critical Zones: {metrics['critical_zones']}</span>
<span class="kpi">Active Alerts: {metrics['active_alerts']}</span>
<span class="kpi">Coverage: {metrics['monitoring_coverage']:.1f}%</span>
<span class="kpi">Sensor Health: {metrics['sensor_health']:.1f}%</span>
</div>

<h2>Zone Status</h2>
<table><tr><th>Zone</th><th>Health</th><th>Risk Score</th><th>Area (ac)</th></tr>
{zone_rows}</table>

<h2>Recent Alerts</h2>
<table><tr><th>ID</th><th>Type</th><th>Severity</th><th>Risk</th><th>Status</th></tr>
{alert_rows}</table>

<h2>Interventions</h2>
<table><tr><th>ID</th><th>Type</th><th>Target Area (ac)</th><th>Status</th></tr>
{intervention_rows}</table>

<h2>Recent Scans</h2>
<table><tr><th>ID</th><th>Type</th><th>Coverage</th><th>Timestamp</th></tr>
{scan_rows}</table>

<p><em>Generated by CitrusGuardAI. Demo data — not field-validated.</em></p>
</body></html>"""
    return html
